title: JasonXiang's Homepage
page-top-title: JasonXiang
top-section-bg-text: Be what you wanna be
home-subtitle: Myname&ensp;|&ensp;JasonXiang
copyright-text: '&copy; Yourname 2023-2025. All Rights Reserved.'

site_name: "JasonXiang"
site_description: "控制科学与工程/硕士在读"
email: "1661825351@qq.com"
